server:
  port: 9090
  servlet.context-path: "/api"

spring.application:
    name: auth-server

spring.jpa:
  hibernate:
    ddl-auto: update
  properties:
      hibernate.format_sql: true
  show-sql: true

spring.mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

spring.security:
    oauth2:
      authorizationserver:
        client:
          interviewgether:
            registration:
              client-id: ${REGISTERED_CLIENT_ID}
              client-secret: ${REGISTERED_CLIENT_SECRET}
              client-authentication-methods:
                - client_secret_basic
              redirect-uris:
                - ${REGISTERED_CLIENT_REDIRECT_URI}
              authorization-grant-types:
                - authorization_code
                - refresh_token
              scopes:
                - openid
                - profile
            require-authorization-consent: true
            require-proof-key: true

      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging.level:
  org.springframework.security: DEBUG

webClientUrl: "http://localhost:9091"
registeredClient:
  url: ${REGISTERED_CLIENT_URL}

# ToDo: Move secrets to secret.yml file later